repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E501
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: flake8
    -   id: requirements-txt-fixer
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: fix-encoding-pragma

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.4'
    hooks:
    -   id: isort
